name: CI

on:
  pull_request:
    types: [opened, synchronize]

env:
  PR_ID: ${{ github.event.pull_request.number }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}
  # PR_REF: ${{ github.event.pull_request.head.ref }}

jobs:
  Clone:
    uses: ./.github/workflows/_Clone-linux.yml
    with:
      PR_ID: ${{ github.event.pull_request.number }}
      COMMIT_ID: ${{ github.event.pull_request.head.sha }}

  # SOT:
  #   uses: ./.github/workflows/_SOT.yml
  #   needs: Clone
  #   with:
  #     PR_ID: ${{ PR_ID }}
  #     COMMIT_ID: ${{ COMMIT_ID }}

  # Py3:
  #   uses: ./.github/workflows/_Py3.yml
  #   needs: Clone
  #   with:
  #     PR_ID: ${{ PR_ID }}
  #     COMMIT_ID: ${{ COMMIT_ID }}
