name: PR-CI-Clone

on:
  push:
    branches: [ "CI_migrate_new" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  Clone:
    environment: Paddle-CI
    runs-on: ubuntu-latest
    steps:
    - name: Clone paddle
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Download bos client
      env:
        WORK: "/home/runner/work/Paddle"
        AK: ${{ secrets.BOS_AK }}
        SK: ${{ secrets.BOS_SK }}
      run: |
        git checkout -b test
        tar -zcf ${WORK}/Paddle-action.tar.gz ${WORK}/Paddle -P
        echo "current dir is $PWD"
        cd $WORK
        echo "current dir is $PWD"
        python -m pip install bce-python-sdk==0.8.74
        wget -q --no-proxy -O ${WORK}/bos_upload.py  https://paddle-docker-tar.cdn.bcebos.com/bos_upload.py --no-check-certificate

    - name: Push to Bos
      env:
        WORK: "/home/runner/work/Paddle"
        PR_ID: test # ${{ github.event.pull_request.number }}
        COMMIT_ID: test # ${{ github.event.pull_request.head.sha }}
      run: |
        set -x
        cd $WORK
        echo $PWD
        python3  $WORK/bos_upload.py $WORK/Paddle-action.tar.gz xly-devops/PR/Paddle/${PR_ID}/${COMMIT_ID}

    # - name: Upload Paddle artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: Paddle
    #     path: Paddle.tar.gz
