name: Clone-linux

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

env:
  PR_ID: ${{ github.event.pull_request.number }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}

jobs:
  Clone:
    # Don't run on forked repos.
    if: github.repository_owner == 'PaddlePaddle'
    runs-on:
      group: HK-Clone
    env:
      BRANCH: develop
      bos_file: "~/bos_upload.py"
    steps:
    - name: Clone paddle
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.base.ref }}
        submodules: 'recursive'
        fetch-depth: 1000

    - name: Merge PR to test branch
      run: |
        git fetch origin pull/${PR_ID}/merge
        git checkout -b test FETCH_HEAD

    - name: Download bos client
      run: |
        if [ ! -f "${bos_file}" ]; then
          wget -q --no-proxy -O "${bos_path}"  https://paddle-docker-tar.cdn.bcebos.com/bos_upload.py --no-check-certificate
        fi

    - name: Push paddle-action.tar.gz to bos
      env:
        AK: ${{ vars.AK }}
        SK: ${{ vars.SK }}
      run: |
        cd ..
        tar -zcf Paddle.tar.gz Paddle
        python -m pip install bce-python-sdk==0.8.74
        python ${bos_file} Paddle.tar.gz paddle-github-action/PR/Paddle/${PR_ID}/${COMMIT_ID}

  # Scheduling:
  #   runs-on:
  #     group: HK-Clone
  #   needs: Clone
  #   uses: ./.github/workflows/Scheduling.yml
  #   with:
  #     PR_ID: ${PR_ID}
  #     COMMIT_ID: ${COMMIT_ID}
