name: PR-CI-Clone

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Paddle
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Push Paddle to BOS
      env:
        PR_ID: ${{ github.event.pull_request.number }}
        COMMIT_ID: ${{ github.event.pull_request.head.sha }}
      run: |
        echo "$PWD"
        echo "$PR_ID"
        echo "$COMMIT_ID"
        git checkout -b test
        cd ..
        python3 -m pip install bce-python-sdk==0.8.74
        tar -zcf Paddle.tar.gz Paddle
        wget -q --no-proxy -O bce_whl.tar.gz  https://paddle-docker-tar.bj.bcebos.com/home/bce_whl.tar.gz --no-check-certificate
        tar xf bce_whl.tar.gz
        # export PATH="/home/runner/work/Paddle/bce-python-sdk-0.8.27:$PATH"
        python3  bce-python-sdk-0.8.27/BosClient.py Paddle.tar.gz xly-devops/PR/Paddle/${PR_ID}/${COMMIT_ID}

    # - name: Upload Paddle artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: Paddle
    #     path: Paddle.tar.gz
