name: PR-CI-Clone

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
    - name: Clone paddle
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Download bos client
      env:
        WORK: "/home/runner/work/Paddle"
      run: |
        git checkout -b test
        tar -zcf ${WORK}/Paddle.tar.gz ${WORK}/Paddle
        wget -q --no-proxy -O ${WORK}/bce_whl.tar.gz  https://paddle-docker-tar.bj.bcebos.com/home/bce_whl.tar.gz --no-check-certificate
        tar xf ${WORK}/bce_whl.tar.gz

    - name: Push to Bos
      env:
        PR_ID: ${{ github.event.pull_request.number }}
        COMMIT_ID: ${{ github.event.pull_request.head.sha }}
      run: |
        python3  BosClient.py Paddle.tar.gz xly-devops/PR/Paddle/${PR_ID}/${COMMIT_ID}
      working-directory: ${GITHUB_WORKSPACE}/bce-python-sdk-0.8.27

    # - name: Upload Paddle artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: Paddle
    #     path: Paddle.tar.gz
