name: PR-CI-Clone

on:
  pull_request:
    branches:
      - develop

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Modify branch name
      run: |
        git branch -m test

    - name: tar Paddle
      runs:|
        tar --exclude=Paddle.tar.gz -zcf Paddle.tar.gz .

    - name: Download BOS client
      run: |
        set +x
        wget -q --no-proxy -O bce_whl.tar.gz  https://paddle-docker-tar.bj.bcebos.com/home/bce_whl.tar.gz --no-check-certificate
        set -x
        tar xf bce_whl.tar.gz
        echo "bos_client=bce-python-sdk-0.8.27/BosClient.py" >> $GITHUB_ENV

    - name: Push to BOS
      run: |
        python3  ${{ env.bos_client }} Paddle.tar.gz xly-devops/PR/Paddle/${{ github.event.pull_request.number }}/${{ github.event.pull_request.head.sha }}

    # - name: Upload Paddle artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: Paddle
    #     path: Paddle.tar.gz
