name: Scheduling

on:
  workflow_call:
    inputs:
      PR_ID:
        description: 'PR number'
        required: true
        type: string
      COMMIT_ID:
        description: 'commit number'
        required: true
        type: string

jobs:
  SOT:
    uses: ./.github/workflows/PR-CI-SOT.yml
    with:
      PR_ID: ${PR_ID}
      COMMIT_ID: ${COMMIT_ID}
