name: test-merge

on:
  pull_request:

jobs:
  test-merge:
    # Don't run on forked repos.
    if: github.repository_owner == 'PaddlePaddle'
    runs-on: ubuntu-latest
    env:
      PR_ID: ${{ github.event.pull_request.number }}
      COMMIT_ID: ${{ github.event.pull_request.head.sha }}
      BRANCH: develop
    steps:
    - name: Clone paddle
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 1000

    - name: Merge PR to test branch
      run: |
        git fetch origin pull/${PR_ID}/merge
        git checkout -b test FETCH_HEAD
        git log
