name: workflow-run-test

on:
  pull_request:
  workflow_run:
    workflows: [Codestyle-Check]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "hh"
